obj-y   := hw29766097p0p512p1024p2x2p2x2p2x2.o
obj-y	+= clock.o
obj-y	+= cmd_bootqca.o
obj-y += cmd_sec_auth.o
obj-$(CONFIG_SMP_CMD_SUPPORT)	+= cmd_runmulticore.o
obj-y += fdt_fixup.o
obj-$(CONFIG_QCA_APPSBL_DLOAD) += crashdump.o
