#!/bin/sh

config="/bin/config"

if [ "$($config get dns_hijack)" = "1" ]; then
	# Enable DNS Hijack mode
	echo "DNS-Hijack: enable dns_hijack!!!" >/dev/console 
	killall -SIGUSR1 dnsmasq
	sleep 1
	killall -SIGUSR1 dnsmasq
else
	echo "DNS-Hijack: disable dns_hijack!!!" >/dev/console
	# Disable DNS Hijack mode
	killall -SIGUSR2 dnsmasq
	sleep 1
	killall -SIGUSR2 dnsmasq
	#Disable nmrp function after install done
	artmtd -w nmrp 0

	#restart dnsmasq if region is PR for xunyou
	region="$(/sbin/artmtd -r region | grep REGION | awk '{print $2}')"
	if [ "$region" = "PR" ]; then
		/etc/init.d/dnsmasq restart
	fi

fi
