#!/bin/sh
# Copyright (C) 2006 OpenWrt.org 
rae_partion=$(part_dev rae)
panic_partion=$(part_dev crashinfo)
RAE_DIR=/tmp/router-analytics

START=99

#only run on base, MR2.x  use /tmp/orbi_type judge the orbi type
start() {
	local enable_ra=`/bin/config get agree_collect_TC`

	killall -9  aws-iot
	rm /var/run/aws_iot.pid
	if [ "$enable_ra" == "0" ]; then
		/usr/sbin/aws-iot -t 86400 -o eventtype4 
		/bin/config set aws_start_flag=2
		/bin/config commit
	else
		/usr/sbin/aws-iot &
		/bin/config set aws_start_flag=1
		/bin/config commit
	fi

}

stop() 
{
	killall -9 aws-iot
	rm /var/run/aws_iot.pid
}

restart()
{
	stop
	start
}

update()
{
	cd $RAE_DIR
	FILES="policy_version rae_version RAE_Policy.json /usr/sbin/aws-iot /usr/sbin/data_collector /usr/sbin/subscribe_publish_sample"
	tar -zcf rae.tar.gz $FILES
	dd if=/dev/zero bs=1024k count=1 |tr "\000" "\377" >1024kdata
	dd if=rae.tar.gz of=1024kdata
	flash_erase $rae_partion 0 0
	cat 1024kdata > $rae_partion
	rm rae.tar.gz
	rm 1024kdata
	echo 1 >$RAE_DIR/status
}

check()
{
	mkdir $RAE_DIR
	echo 0 >$RAE_DIR/status
	dd if=$rae_partion of=/tmp/rae.tar.gz
	tar zxf /tmp/rae.tar.gz -C $RAE_DIR/
	tar_status=$?
	if [ -s $RAE_DIR/rae_version -a -s $RAE_DIR/policy_version -a -s $RAE_DIR/usr/sbin/aws-iot -a -s $RAE_DIR/usr/sbin/data_collector -a -s $RAE_DIR/usr/sbin/subscribe_publish_sample -a -s $RAE_DIR/RAE_Policy.json ];then
		mv $RAE_DIR/usr/sbin/* /usr/sbin/
		echo 1 >$RAE_DIR/status
		rm /tmp/rae.tar.gz -rf
		rm $RAE_DIR/usr -rf
	fi
}

boot()
{
	#As NTGR Analytic_opt-in_opt-out spec:
	#There's a default value NVRAM RA_enable, WW, GR, PR SKU default is 0 not send RA, other SKU default is 1, will send RA
	#After user opt-in/opt-out analytic, after firmware upgrade/downgrade, the setting should be the same
	region=`artmtd -r region |grep REGION |awk -F " " '{printf $2}'`
	if [ "x$(/bin/config get RA_enable)" = "x" ];then
		if [ "$region" = "WW" -o "$region" = "GR" -o "$region" = "PR" ];then
			/bin/config set agree_collect_TC=0
			/bin/config set RA_enable=0
		else
			/bin/config set agree_collect_TC=1
			/bin/config set RA_enable=1
		fi
	fi

	if [ "x$(/bin/config get RA_stage)" = "x" ];then
	/bin/config set RA_stage=prod
	fi
	if [ -s /etc/reboot_reason ]; then
		local reboot_reason=`cat  /etc/reboot_reason`
		echo $reboot_reason > /tmp/reboot_reason
		rm -fr /etc/reboot_reason
	fi

	/bin/config set internetDisconnDuration=0
	/bin/config set gwDisconnDuration=0

	dd if=$panic_partion of=/tmp/crash_log bs=131072 count=2
	if [ -f /tmp/ramoops/crash_log ]; then
		echo 1 > /tmp/reboot_reason

		cp /tmp/ramoops/crash_log /tmp/crash_aws_log
		/bin/config set eventtype=0
	fi

	check
	 /bin/config set cpu_flag=1
	 /bin/config set memory_flag=1
	if [ "x$(/bin/config get lastRebootReason)" = "x" ];then
		echo 0 > /tmp/reboot_reason
	else
		if [ ! -f /tmp/reboot_reason ];then
			echo $(/bin/config get lastRebootReason) > /tmp/reboot_reason
		fi
	fi

	 /bin/config set eventtype=0
	 /bin/config commit
		if [ "$(cat $RAE_DIR/status)" = "1" ]; then
			start
		fi

	# NTGR request that every reboot should check for update
	/usr/sbin/ra_check

	/sbin/icqm &
}

cpu_test()
{
	for in in `seq $1`
	do 
		echo -ne "i=0;
		while true
		do 
			i=i+1;
		done" | /bin/sh &
		
	done
}

memory_test()
{
	if [ "$1" = 1 ]; then
		mkdir /tmp/memory
		mount -t tmpfs -o size=280M tmpfs /tmp/memory
		dd if=/dev/zero of=/tmp/memory/block
	else
		rm /tmp/memory/block
		umount /tmp/memory
		rmdir /tmp/memory
	fi
}

disable()
{
	killall -9 aws-iot
	rm /var/run/aws_iot.pid
	killall -9 ra_check
	rm /var/run/ra_check.pid
}
case "$1" in 
	"boot")
		boot $2
	;;
	"start")
		start
	;;
	"stop")
		stop
	;;
	"disable")
		disable
	;;
	"restart")
		restart
	;;
	"update")
		update
	;;
	"check")
		check
	;;
	"cpu")
		cpu_test  $2
	;;
	"memory")
		memory_test $2
	;;
	*)
		echo "Unknow command" > /dev/console
		echo "Usage: $0 boot|start|stop|restart|update|disable" > /dev/console
	;;
esac
