#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1

START=50

start() {

	user_exists http || user_add http
	[ -d /var/log/lighttpd ] || {
		mkdir -m 0775 -p /var/log/lighttpd
		chgrp www-data /var/log/lighttpd 2>/dev/null
	}
	touch /www/soapapi
	touch /www/shares
	touch /www/404_error
	if [ "x`/bin/config get force_https`" = "x1" ]; then {
		service_start /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd_https.conf
	}
	else {
		service_start /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
	}
	fi
	/usr/sbin/fw-checking
	/usr/sbin/hash-data -p
}

stop() {
	service_stop /usr/sbin/lighttpd
	/usr/bin/killall fw-checking
}

restart() {
	service_stop /usr/sbin/lighttpd
	/usr/bin/killall fw-checking
	if [ "x`/bin/config get force_https`" = "x1" ]; then {
		service_start /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd_https.conf
	}
	else {
		service_start /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
	}
	fi
	/usr/sbin/fw-checking
	/usr/sbin/hash-data -p
}
