#!/bin/sh /etc/rc.common
# Copyright (C) 2020-2021 Delta Networks Inc.


START=50

CONFIG=/bin/config
CONFIG_FILE="/tmp/net-cgi.conf"

HOST_NAME=$(cat /hardware_version)
HW_ID=$($CONFIG get dgc_hw_id)
DEVICE_NAME_LENGTH=32
RAX120_WIFI_DRIVER=1
LIMIT_DOWNGRADE=1
ENFORCEDLY_UPGRADE_ON_CDLESS=1
RAX120_SERIES=v2
UPDATE_OOKLA_COMMAND=1
SUPPORT_RA_OPT_IN_OPT_OUT=1
SUPPORT_PCCW_IGMP=1

config() {
	printf "### GENERATED AUTOMATICALLY, PLEASE DON'T EDIT MANUALLY\n"

	printf "%s\n" \
		"nc_upg_mod \"${UPG_MOD}\"" \
		"nc_hw_id \"${HW_ID}\"" \
		"nc_device_name_length \"${DEVICE_NAME_LENGTH}\"" \
		"nc_rax120_wifi_driver \"${RAX120_WIFI_DRIVER}\"" \
		"nc_limit_downgrade \"${LIMIT_DOWNGRADE}\"" \
		"nc_enforcedly_upgrade_on_cdless \"${ENFORCEDLY_UPGRADE_ON_CDLESS}\"" \
		"nc_rax120_series \"${RAX120_SERIES}\"" \
		"nc_update_ookla_command \"${UPDATE_OOKLA_COMMAND}\"" \
		"nc_support_ra_opt_in_opt_out \"${SUPPORT_RA_OPT_IN_OPT_OUT}\"" \
		"nc_support_pccw_igmp \"${SUPPORT_PCCW_IGMP}\"" \
		""
}
start() {
	echo "net-cgi is managed by lighttpd!!!"
	config > $CONFIG_FILE
}

stop() {
	echo "net-cgi is managed by lighttpd!!!"
}

restart() {
	echo "net-cgi is managed by lighttpd!!!"
	start
}

boot() {
	start
}
