#!/bin/sh /etc/rc.common

START=49

boot() {
    sw_feature=$(artmtd -r sw_feature | tr 'a-z' 'A-Z')
    if [ "${sw_feature:12:2}" = "0X" ]; then
        # 1. transfer sw_feature from 16#hex to 2#bin, and fulfill with 32 bits
        # 2. reverse order
        sw_feature_bin=$(echo "ibase=16;obase=2; ${sw_feature:14}" | bc | xargs printf "%032d" |\
                         awk '{for(i=1;i<=length;i++){line=substr($0,i,1) line}} END {print line}')
        /bin/config set sw_feature_bin=${sw_feature_bin}

        # default_on_https flag is the bit #4
        if [ "$(echo ${sw_feature_bin} | cut -b 4)" = "1" -o "${region}" = "AP" ]; then
			config_dgc_func_default_https="$(/bin/config get dgc_func_have_default_on_https)"
			if [ "${config_dgc_func_default_https}" = "" -o "${config_dgc_func_default_https}" = "0" ]; then
				echo "======== [sw_feature] enable defaults_on_https" > /dev/console
            	/bin/config set force_https=1
            	/bin/config set dgc_func_have_default_on_https=1
			fi
        else
            /bin/config set dgc_func_have_default_on_https=0
        fi
    fi
}
