#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

boot() {
	local commit_flag=0

	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	mkdir -p /tmp/.jail
	mkdir -p /tmp/cache/wireless/
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf
	ln -s /usr/sbin/rmmod /sbin/rmmod
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	board_id=$(devmem 0x0194D000)
	#0x200D0101 //HK1.1
	#0x200D0102 //HK1.2
	#0x200D0200 //HK2.0
	[ "x$board_id" = "x0x200D0200" ] && echo "RAX120v2" >/module_name
	# datalib must starts up first
	ifconfig lo up
	/bin/datalib Base

	# Enable collect console in boot script
	[ "$($CONFIG get debug_boot_up)" = "1" ] && {
		echo enable > /sys/devices/platform/soc/78b3000.serial/console
		/sbin/console_log.sh &
	}

	# preset hostname
	echo "$(/bin/config get netbiosname)" > /proc/sys/kernel/hostname
	/sbin/printhosts

	# init gpio
	/sbin/init-gpio

	insmod /lib/ufsd/jnl.ko
	insmod /lib/ufsd/ufsd.ko

	#/sbin/kwilt init

	/sbin/kmodloader

	/bin/board_detect
	uci_apply_defaults
	
	# temporary hack until configd exists
	/sbin/reload_config

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}

	# generate the firewall rule file after loading the configuration data.
	/usr/sbin/net-wall rule
	/etc/init.d/ubootupgrade.sh crash

	# start SIP ALG module
	/sbin/cmd_sipalg

	# indicate the system first boot for first log
	$CONFIG set syslog_up_first=0

	# Load Default QoS rules if needed.
	qos_dft="$(/bin/config get qos_list_default)"
	if [ "$qos_dft" = "1" ]; then
		count=1
		while :
		do
			qos_rule="$(/bin/config get qos_dft_list$count)"
			if [ "x$qos_rule" = "x" ]; then
				break;
			fi
			/bin/config set qos_list$count="$qos_rule"

			count=`expr $count + 1`
		done

		count=`expr $count - 1`
		echo "$count QoS default rules are Loaded!"

		/bin/config set qos_list_default="0"
		commit_flag=1
	fi

	# fetch language to /tmp/lang_file
	mtdn=`grep language /proc/mtd | awk -F ':' '{print $1}' | awk -F 'd' '{print $2}'`
	/usr/sbin/nanddump /dev/mtd$mtdn -f /tmp/lang_file &
	#read wpspin from flash to /tmp/wpspin
	/sbin/artmtd -r wpspin
	#read serial number from flash to /tmp/Seria_Number
	/sbin/artmtd -r sn
	#read wan mac from flash to /tmp/wan_mac
	/sbin/artmtd -r mac
	#read hw id from flash to /tmp/board_hw_id
	/sbin/artmtd -r board_hw_id | cut -f 2 -d ':' > /tmp/board_hw_id
	#read model id from flash to /tmp/board_model_id
	/sbin/artmtd -r board_model_id | cut -f 2 -d ":" > /tmp/board_model_id
	# Check the Board Data region and reset Time Zone & Wirless Region & GUI Region.
	region="$(/sbin/artmtd -r region | grep REGION | awk '{print $2}')"
	if [ "x$(/bin/config get board_region_default)" = "x1" ]; then
	
		module_name=$(cat /module_name)
		/bin/config set netbiosname=$module_name
		/bin/config set Device_name=$module_name
		/bin/config set wan_hostname=$module_name
		/bin/config set upnp_serverName=$module_name
		/bin/config set bridge_netbiosname=$module_name
		/bin/config set ap_netbiosname=$module_name

		/bin/config set endis_wl_radio="1"
		/bin/config set endis_wla_radio="1"

		case "$region" in
		#when region setting on flash's board data area is RU
		RU)
			/bin/config set wla_country="19"
			/bin/config set wl_country="19"
			/bin/config set ntp_server="GMT-4"
			/bin/config set ntpserver_select="GMT-4"
			/bin/config set ntp_hidden_select="27"
			/bin/config set time_zone="GMT-4"
			/bin/config set email_ntpserver="GMT-4"
			/bin/config set region_flag="DISABLED"
			;;
		#when region setting on flash's board data area is GR
		GR)
			/bin/config set wla_country="4"
			/bin/config set wl_country="4"
			/bin/config set ntp_server="GMT-1"
			/bin/config set ntpserver_select="GMT-1"
			/bin/config set ntp_hidden_select="19"
			/bin/config set time_zone="GMT-1"
			/bin/config set email_ntpserver="GMT-1"
			;;
		#when region setting on flash's board data area is PR
		PR)
			/bin/config set wla_country="11"
			/bin/config set wl_country="11"
			/bin/config set ntp_server="GMT-8"
			/bin/config set ntpserver_select="GMT-8"
			/bin/config set ntp_hidden_select="33"
			/bin/config set time_zone="GMT-8"
			/bin/config set email_ntpserver="GMT-8"
			/bin/config set wla_hidden_channel="153"
			/bin/config set wla_channel="153"
			;;
		#when region setting on flash's board data area is BZ
		BZ)
			/bin/config set wla_country="9"
			/bin/config set wl_country="9"
			/bin/config set ntp_server="GMT+3"
			/bin/config set ntpserver_select="GMT+3"
			/bin/config set ntp_hidden_select="14"
			/bin/config set time_zone="GMT+3"
			/bin/config set email_ntpserver="GMT+3"
			;;
		#when region setting on flash's board data area is IN
		IN)
			/bin/config set wla_country="12"
			/bin/config set wl_country="12"
			/bin/config set ntp_server="GMT-5:30"
			/bin/config set ntpserver_select="GMT-5:30"
			/bin/config set ntp_hidden_select="30"
			/bin/config set time_zone="GMT-5:30"
			/bin/config set email_ntpserver="GMT-5:30"
			;;
		#when region setting on flash's board data area is KO
		KO)
			/bin/config set wla_country="7"
			/bin/config set wl_country="7"
			/bin/config set ntp_server="GMT-9"
			/bin/config set ntpserver_select="GMT-9"
			/bin/config set ntp_hidden_select="35"
			/bin/config set time_zone="GMT-9"
			/bin/config set email_ntpserver="GMT-9"
			;;
		#when region setting on flash's board data area is JP
		JP)
			/bin/config set wla_country="6"
			/bin/config set wl_country="6"
			/bin/config set ntp_server="GMT-9"
			/bin/config set ntpserver_select="GMT-9"
			/bin/config set ntp_hidden_select="35"
			/bin/config set time_zone="GMT-9"
			/bin/config set email_ntpserver="GMT-9"
			/bin/config set region_flag="DISABLED"
			;;
		#when region setting on flash's board data area is NA
		NA|US)
			/bin/config set wla_country="10"
			/bin/config set wl_country="10"
			/bin/config set wla_hidden_channel="153"
			/bin/config set region_flag="DISABLED"
			/bin/config set ntp_server="GMT+8"
			/bin/config set ntpserver_select="GMT+8"
			/bin/config set ntp_hidden_select="4"
			/bin/config set time_zone="GMT+8"
			/bin/config set email_ntpserver="GMT+8"
			;;
		#when region setting on flash's board data area is AU
		AU)
			/bin/config set wla_country="2"
			/bin/config set wl_country="2"
			/bin/config set ntp_server="GMT-10"
			/bin/config set ntpserver_select="GMT-10"
			/bin/config set ntp_hidden_select="37"
			/bin/config set time_zone="GMT-10"
			/bin/config set email_ntpserver="GMT-10"
			;;
		#when region setting on flash's board data area is CA
		CA)
			/bin/config set wla_country="3"
			/bin/config set wl_country="3"
			/bin/config set ntp_server="GMT+5"
			/bin/config set ntpserver_select="GMT+5"
			/bin/config set ntp_hidden_select="10"
			/bin/config set time_zone="GMT+5"
			/bin/config set email_ntpserver="GMT+5"
			;;
		WW)
			/bin/config set wla_country="4"
			/bin/config set wl_country="4"
			/bin/config set ntp_server="GMT-0"
			/bin/config set netserver_select="GMT-0"
			/bin/config set time_zone="GMT-0"
			/bin/config set email_ntpserver="GMT-0"
			;;
		*)
			#If firmware can not recornize
			/bin/echo "The firmware can not recognize the Region in flash!" > /dev/console
			/bin/config set endis_wl_radio="0"
			/bin/config set endis_wla_radio="0"
			/bin/echo "Disable wireless function!" > /dev/console
			/bin/config set wla_country="-1" 
			/bin/config set wl_country="-1"
			/bin/config set ntp_server="GMT-0"
			/bin/config set netserver_select="GMT-0"
			/bin/config set time_zone="GMT-0"
			/bin/config set email_ntpserver="GMT-0"
			;;
		esac
		/bin/config set board_region_default="0"
		commit_flag=1
	else
		#NAS, CNS, PRS, JPS sku – We lock Wireless Region on these SKUs, so no further action
		#RAX120 need to follow new spec of wireless region on router web GUI
		#   After the new FW upgrade and the region is removed, the region shall change back to the default region and its already certificated Tx power for that SKU. 
		#For example, a Korea user bought KO SKU unit but he set to “Asia” wireless region. After the new FW upgrade to his unit but “Asia” region has been removed in new FW, then this unit must select back to original Korea wireless region and use certificated TX power for Korea. 
		#Note: If the default region has lower TX power than the removed region that the customer originally selected, they may notice the performance drop after the FW upgrade. if default region has higher TX power, the customer will get the performance boost, but it could violate the local regulation. Whatever, since the product is not certified for those regions, selling the product into those regions has the legal concern.
		#Australia 2
		#Europe 4
		#Korea 7
		#Singapore 20
		#Hong Kong 22

		if [ "$region" != "NA" -a "$region" != "CN" -a "$region" != "PR" -a "$region" != "JP" ];then
			region_code=$(/bin/config get wl_country)
			if [ "x$region_code" != "x2" -a "x$region_code" != "x4" -a "x$region_code" != "x7" -a "x$region_code" != "x20" -a "x$region_code" != "x22" ];then
				/bin/config set wl_htmode=HT40
				/bin/config set wla_htmode=HT80
				/bin/config set wla_hidden_channel=44
				/bin/config set wl_hidden_channel=0
				case "$region" in
				#when region setting on flash's board data area is GR
				GR)
					/bin/config set wla_country="4"
					/bin/config set wl_country="4"
					;;
				#when region setting on flash's board data area is BZ
				BZ)
					/bin/config set wla_country="9"
					/bin/config set wl_country="9"
					;;
				#when region setting on flash's board data area is IN
				IN)
					/bin/config set wla_country="12"
					/bin/config set wl_country="12"
					;;
				#when region setting on flash's board data area is KO
				KO)
					/bin/config set wla_country="7"
					/bin/config set wl_country="7"
					;;
				#when region setting on flash's board data area is AU
				AU)
					/bin/config set wla_country="2"
					/bin/config set wl_country="2"
					;;
				WW)
					/bin/config set wla_country="4"
					/bin/config set wl_country="4"
					;;
				*)
					;;
				esac
			fi
		fi
	fi

	# Wireless security pre-set
	id_dft="$(/bin/config get default_ssphrase)"
	if [ "$id_dft" = "1" ]; then
		/sbin/artmtd -r ssid
		/sbin/artmtd -r passphrase

		if [ -s /tmp/ssid-setted ] && [ -s /tmp/passphrase-setted ]; then
			id_set=$(awk '{print $1}' /tmp/ssid-setted)
			ps_set=$(awk '{print $1}' /tmp/passphrase-setted)

			/bin/config set wl_ssid="$id_set"
			/bin/config set wla_ssid="$id_set-5G"
			/bin/config set wl_wpa2_psk="$ps_set"
			/bin/config set wla_wpa2_psk="$ps_set"
			/bin/config set wl_sectype="4"
			/bin/config set wla_sectype="4"
			/bin/config set wps_status="5"
			/bin/config set wla_wps_status="5"

			# set SSID of guest netwroks according to Home Router GUI Redesign Specification Rev10 section 6.3
			/bin/config set wlg1_ssid="NETGEAR-Guest"
			/bin/config set wla1_ssid="NETGEAR-5G-Guest"
		fi
		/bin/config set default_ssphrase="0"
		commit_flag=1
	fi

	# Dal/Xagent/Readycloud Force NVRAM setting
	DAL_NVRAM_DATA_FLAG="20200518"
	if [ "$(/bin/config get dal_nvram_data_flag)" != "$DAL_NVRAM_DATA_FLAG" ]; then
		/bin/config set leafp2p_remote_url="https://peernetwork.netgear.com/peernetwork/services/"
		/bin/config set leafp2p_service_0="RouterRemote,0,1,1,1,1,6:135,6:136,6:137,6:138,6:139,6:445,6:548,17:135,17:136,17:137,17:138,17:139,17:445,17:548"
		/bin/config set readycloud_remote_certificate="/opt/xagent/certs/ca-bundle-mega.crt"
		/bin/config set dal_nvram_data_flag="$DAL_NVRAM_DATA_FLAG"
		commit_flag=1
	fi

	[ "$commit_flag" = "1" ] && /bin/config commit
	
	#Enable factory test mode
	if [ "x$(/bin/config get factory_mode)" = "x1" ]; then
		/bin/touch /tmp/factory_test
		/bin/config set led_blinking_setting="2"
		echo "reset" > /proc/simple_config/button_test
	fi

	# Disable USB power supply
#	echo 0 > /proc/simple_config/usb5v_0
#	echo 0 > /proc/simple_config/usb5v_1
	
	#Enable fan ctrl
	if [ "$(/bin/config get factory_mode)" = "1" ]; then
		echo 0 > /sys/bus/i2c/devices/0-0049/fan1_target
		echo 0 > /sys/bus/i2c/devices/0-003e/fan1_target
	else
		/sbin/temp_ctrl.sh 30 200 60 & #temp_ctrl.sh [ctrl_cycle] [float_rang] [trigger_temp]
	fi

    # download AQR firmware to AQR phy
	aq-fw-download /lib/firmware/AQR_phy_firmware miireg 7
	sleep 1
	ssdk_sh debug phy set 7 0x4004c441 0x8

	mkdir /tmp/config
	echo "root:!:0:0:root:/tmp:/bin/ash" >> /tmp/config/passwd

#Check config file
#
#If remote management is enabled → set NVram value “remotemgmt = 1” → keeps function work and show GUI page 
#
#If remote management is disabled
#-> set Nvram value “remotemgmt = 0”
#-> remove GUI page (req1)
#
#*default set Nvram value “remotemgmt = 0”
#remote_endis

	if [ "$(/bin/config get remote_endis)" = "1" ];then
		/bin/config set remotemgmt=1
	else
		/bin/config set remotemgmt=0
	fi

}
