# Programs
XSLTPROC = xsltproc
XMLLINT = xmllint
PNGTOPNM = 
INKSCAPE = 
PNMTOPS = 
HTML2TEXT = 
DB2TEXI = 
MAKEINFO = 
PLUCKERBUILD = 
DBLATEX = dblatex
RM = rm
PERL = perl

# Paths
OUTPUTDIR = output
ARCHIVEDIR = archive
TEXINFODIR = $(OUTPUTDIR)/texi
SRCDIR = ../
MANPAGEDIR = manpages
SMBDOTCONFDOC = smbdotconf
DOCBOOKDIR = tmp
PSDIR = $(OUTPUTDIR)
PDFDIR = $(OUTPUTDIR)
HTMLHELPDIR = $(OUTPUTDIR)/htmlhelp
PEARSONDIR = $(OUTPUTDIR)/pearson
TXTDIR = $(OUTPUTDIR)/textdocs
HTMLDIR=$(OUTPUTDIR)/htmldocs
PLUCKERDIR=$(OUTPUTDIR)/plucker
DB2LATEX_ARGS = --stringparam latex.documentclass.book letterpaper,11pt,openright,twoside

TARGETS =   htmlman manpages  undocumented
