#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

#START=90

SERVICE_USE_PID=1
SERVICE_PID_FILE=/var/run/ndppd.pid
CONFIG="/bin/config"
NDPROXY_CONFIG="/etc/ndppd.conf"
WAN=brwan
LAN=br0

ndproxy_write_config() {
   local lan_ip6=$(ifconfig $LAN |grep "inet6 addr" |grep -v "Link" |awk '{print $3}' |head -n 1)
   local lan_prefix=${lan_ip6%%/*}
   local lan_prefix_len=${lan_ip6##*/}

   printf 'proxy %s {\n' "$WAN"
   printf 'router yes\n'
   printf 'timeout 500\n'
   printf 'ttl 30000\n'

   printf 'rule %s/%s {\n' "$lan_prefix" "$lan_prefix_len"
        printf 'static\n'
   printf '}\n'


   if [ "x`$CONFIG get ipv6_type`" = "xv6plus" ]; then
	   local mape_ip=`ifconfig map-e |grep "inet6 addr" |grep -v "Link" |awk '{print $3}' |head -n 1`
	   if [ -n "$mape_ip" ]; then
			printf 'rule %s/%s {\n' "${mape_ip%%/*}" "${mape_ip##*/}"
				printf 'static\n'
			printf '}\n'
	   fi
   fi
   printf '}\n'
}

start() {
	mkdir -p /var/run
	if [ "`$CONFIG get ipv6_type`" = "dslite" -o "x`$CONFIG get ipv6_type`" = "xv6plus" ] && [ "`$CONFIG get enable_nd`" -eq "1" ]; then
		#Write ndproxy configuration
		ndproxy_write_config > $NDPROXY_CONFIG
		/usr/sbin/ndppd -p $SERVICE_PID_FILE -d
	fi
}

stop() {
	killall ndppd
	rm -rf $NDPROXY_CONFIG
}
