#!/usr/bin/env bash
#
# repack.sh <unpack_dir> <new_rootfs> <output.img>
#
# Reassembles a GUI-flashable firmware image from an unpack.sh output dir
# plus a (modified or unmodified) rootfs payload.
#
# use mkdniimg (Netgear's own official image-wrapping tool, from
# their GPL release: tools/firmware-utils/src/mkdniimg.c) to generate the
# 128-byte header AND the 1-byte trailing checksum natively, instead of
# blindly reattaching the ORIGINAL image's header+checksum onto a NEW,
# different payload. That mismatch -- confirmed by reading mkdniimg.c's
# actual algorithm (checksum = 0xff - (sum of header+payload bytes mod
# 256), verified against real stock image checksums) -- is exactly why
# repacked images with any real content change were rejected by the
# router's GUI upload validator ("This firmware file is incorrect!").
#
# device/version/region/hd_id are never hardcoded -- they're parsed by
# unpack.sh from the ORIGINAL image's own header and passed through via
# info.txt, so this adapts to any firmware version/region automatically.
#
set -euo pipefail

# ---- colours (matches build_rootfs.sh) -------------------------------------
C_RESET='\033[0m'
C_BOLD='\033[1m'
C_GREEN='\033[1;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[1;31m'
C_CYAN='\033[1;36m'
C_DIM='\033[2m'

info()  { echo -e "${C_CYAN}==>${C_RESET} ${1}"; }
ok()    { echo -e "${C_GREEN}✓${C_RESET} ${1}"; }
warn()  { echo -e "${C_YELLOW}!${C_RESET} ${1}"; }
fail()  { echo -e "${C_RED}✗ ${1}${C_RESET}"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
MKDNIIMG="${MKDNIIMG_OVERRIDE:-$SCRIPT_DIR/../bin/firmware-utils/mkdniimg}"

echo -e "${C_BOLD}${C_CYAN}"
echo "  ____                       _    "
echo " |  _ \\ ___ _ __   __ _  ___| | __"
echo " | |_) / _ \\ '_ \\ / _\` |/ __| |/ /"
echo " |  _ <  __/ |_) | (_| | (__|   < "
echo " |_| \\_\\___| .__/ \\__,_|\\___|_|\\_\\"
echo "            |_|                   "
echo -e "${C_RESET}"
echo -e "${C_DIM}RAX120v2 firmware repack — chop-and-swap rootfs reassembly${C_RESET}"
echo

UNPACK_DIR="${1:?Usage: repack.sh <unpack_dir> <new_rootfs> <output.img>}"
NEW_ROOTFS="${2:?Missing new_rootfs argument}"
OUTPUT_IMG="${3:?Missing output.img argument}"

INFO_FILE="$UNPACK_DIR/info.txt"
FIT_KERNEL="$UNPACK_DIR/01_fit_kernel_dtb.bin"

# ---- preflight --------------------------------------------------------------
info "Preflight checks"
command -v mkimage >/dev/null 2>&1 || fail "mkimage not found on PATH."
[ -x "$MKDNIIMG" ]    || fail "$MKDNIIMG not found or not executable -- vendored mkdniimg missing."
[ -f "$INFO_FILE" ]   || fail "$INFO_FILE missing — run unpack.sh first."
[ -f "$FIT_KERNEL" ]  || fail "$FIT_KERNEL missing — unpack_dir looks incomplete."
[ -f "$NEW_ROOTFS" ]  || fail "$NEW_ROOTFS not found."
ok "All required inputs present"

info "Loading build parameters from info.txt"
# shellcheck disable=SC1090
source "$INFO_FILE"
for var in UIMAGE_ARCH UIMAGE_OS UIMAGE_TYPE UIMAGE_COMP UIMAGE_LOAD UIMAGE_ENTRY UIMAGE_NAME; do
    [ -n "${!var:-}" ] || fail "info.txt is missing $var — was it generated by a current unpack.sh?"
done
for var in DNI_DEVICE DNI_VERSION; do
    [ -n "${!var:-}" ] || fail "info.txt is missing $var — was it generated by a current unpack.sh (with mkdniimg header parsing)?"
done
# DNI_REGION legitimately empty, DNI_HDID legitimately absent on any firmware
# that never had a hd_id: field to begin with (mkdniimg.c only writes it if
# -H was passed at original build time) -- neither is required non-empty.
ok "Params: arch=$UIMAGE_ARCH os=$UIMAGE_OS type=$UIMAGE_TYPE comp=$UIMAGE_COMP name=\"$UIMAGE_NAME\""
ok "mkdniimg identity: device=$DNI_DEVICE version=$DNI_VERSION region='$DNI_REGION' hd_id=${DNI_HDID:-<none>}"

info "Verifying new rootfs format"
new_magic=$(dd if="$NEW_ROOTFS" bs=1 count=4 2>/dev/null | od -An -tx1 | tr -d ' \n')
# NOTE: -L (dereference) is required here. NEW_ROOTFS is commonly a symlink
new_rootfs_size=$(stat -Lc%s "$NEW_ROOTFS")
if [ "$new_magic" = "68737173" ]; then
    ok "squashfs magic confirmed ('hsqs'), $new_rootfs_size bytes"
else
    warn "New rootfs does not start with squashfs magic (got: $new_magic)."
    warn "Continuing, but this will likely fail to mount if it isn't squashfs."
fi

# ---- rebuild the uImage wrapper --------------------------------------------
info "Generating legacy uImage header for rootfs"
mkimage -A "$UIMAGE_ARCH" -O "$UIMAGE_OS" -T "$UIMAGE_TYPE" -C "$UIMAGE_COMP" \
        -a "$UIMAGE_LOAD" -e "$UIMAGE_ENTRY" -n "$UIMAGE_NAME" \
        -d "$NEW_ROOTFS" "$UNPACK_DIR/new_rootfs.uimage" > /tmp/.mkimage_out 2>&1 \
        || { cat /tmp/.mkimage_out; fail "mkimage failed"; }
sed 's/^/    /' /tmp/.mkimage_out
ok "uImage wrapper built"

# ---- stitch -------------------------------------------------------------
info "Assembling raw payload (FIT+kernel + rootfs uImage -- no header, no checksum yet)"
PAYLOAD="$UNPACK_DIR/one_image_final.bin"
cat "$FIT_KERNEL" "$UNPACK_DIR/new_rootfs.uimage" > "$PAYLOAD"

info "Generating final image via mkdniimg (header + checksum computed natively, correctly, for THIS payload)"
MKDNIIMG_ARGS=(-B "$DNI_DEVICE" -v "$DNI_VERSION" -r "$DNI_REGION")
# -H only added when the original genuinely had a hd_id: field. mkdniimg.c
# writes hd_id whenever -H was passed at all -- even `-H ""` -- so passing
# it unconditionally would inject a hd_id: line into a header that never
# had one, silently changing the header's layout and the checksum it
# produces relative to the original identity we're supposed to be cloning.
[ -n "$DNI_HDID" ] && MKDNIIMG_ARGS+=(-H "$DNI_HDID")
"$MKDNIIMG" "${MKDNIIMG_ARGS[@]}" -i "$PAYLOAD" -o "$OUTPUT_IMG" \
    || fail "mkdniimg failed"
rm -f "$PAYLOAD"
ok "Wrote $OUTPUT_IMG"

# ---- size sanity --------------------------------------------------------
NEW_SIZE=$(stat -c%s "$OUTPUT_IMG")
echo
info "Size check"
echo -e "    ${C_DIM}Original:${C_RESET} ${SOURCE_IMG_SIZE:-unknown} bytes"
echo -e "    ${C_DIM}New:     ${C_RESET} $NEW_SIZE bytes"

if [ -n "${SOURCE_IMG_SIZE:-}" ]; then
    diff_size=$((NEW_SIZE - SOURCE_IMG_SIZE))
    if [ "$diff_size" -gt 2000000 ]; then
        warn "New image is $diff_size bytes LARGER than the original — check partition limits before flashing."
    elif [ "$diff_size" -lt -2000000 ]; then
        warn "New image is significantly SMALLER — did a build step silently fail?"
    else
        ok "Size variance within normal range ($diff_size bytes)"
    fi
fi

# Advisory check against mtd24 "firmware" partition size (0x06400000), if known.
FIRMWARE_PARTITION_SIZE=$((0x06400000))
if [ "$NEW_SIZE" -gt "$FIRMWARE_PARTITION_SIZE" ]; then
    warn "New image ($NEW_SIZE bytes) exceeds mtd24 'firmware' partition size ($FIRMWARE_PARTITION_SIZE bytes)."
    warn "This WILL fail to flash as a whole image. Trim rootfs or investigate before proceeding."
fi

# ---- automatic round-trip diff, if the original source image is still there
echo
info "Round-trip comparison"
if [ -n "${SOURCE_IMG:-}" ] && [ -f "$SOURCE_IMG" ]; then
    src_size=$(stat -c%s "$SOURCE_IMG")
    if [ "$src_size" != "$NEW_SIZE" ]; then
        diff=$((NEW_SIZE - src_size))
        sign=""
        [ "$diff" -gt 0 ] && sign="+" # Add a plus sign if the size increased

        warn "Size mismatch: original=$src_size bytes, repacked=$NEW_SIZE bytes"
        warn "Total firmware size changed by ${sign}${diff} bytes."
        echo -e "    ${C_DIM}This is normal and expected if you intentionally modified the rootfs,${C_RESET}"
        echo -e "    ${C_DIM}or due to differing compression heuristics in your host's mksquashfs tool.${C_RESET}"
    else
        diff_count=$(cmp -l "$SOURCE_IMG" "$OUTPUT_IMG" 2>/dev/null | wc -l || true)
        if [ "$diff_count" -eq 0 ]; then
            ok "Byte-for-byte IDENTICAL to $SOURCE_IMG (sizes match, zero byte diffs)"
        else
        warn "$diff_count byte(s) differ from $SOURCE_IMG"
        if [ "$new_rootfs_size" != "${ROOTFS_PAYLOAD_SIZE:-}" ]; then
            echo "    Rootfs size changed (${ROOTFS_PAYLOAD_SIZE:-?} -> $new_rootfs_size bytes) —"
            echo "    expected if you intentionally modified the rootfs. Diffs beyond the"
            echo "    rootfs-wrapper header (offset ${ROOTFS_UIMAGE_HDR_OFFSET:-?}) are your real change."
        else
            echo "    Rootfs size UNCHANGED — any diffs are unexpected for a pass-through test."
            echo "    First few diffs (relative to rootfs header at offset ${ROOTFS_UIMAGE_HDR_OFFSET:-?}):"
            cmp -l "$SOURCE_IMG" "$OUTPUT_IMG" 2>/dev/null | head -5 | while read -r off b1 b2; do
                rel=$(( (off - 1) - ${ROOTFS_UIMAGE_HDR_OFFSET:-0} ))
                echo "      header offset $rel: $b1 -> $b2 (octal)"
            done || true
        fi
    fi
    fi
else
    warn "Original source image not found at recorded path ($SOURCE_IMG) — skipping comparison"
fi

echo
info "Final header (for visual confirmation)"
mkimage -l "$UNPACK_DIR/new_rootfs.uimage" | sed 's/^/    /'

echo
ok "Repack complete: $OUTPUT_IMG"
