#!/usr/bin/env bash
#
# 002-turbo-fan.sh
#
# Description: Overwrites the factory temp_ctrl.sh with a more aggressive 
#              linear fan curve and strips out Netgear telemetry logging.
# Applied by:  apply_mods.sh (runs in version-sort order via `sort -V`)
#
# ==============================================================================
# apply_mods.sh - FILE NAMING CONVENTIONS & EXECUTION RULES
# ==============================================================================
#
# All files inside mods/ MUST begin with exactly three leading digits (NNN).
# Any file with missing digits, wrong lengths, or prefixes (e.g., 'd010-foo.sh')
# is ignored and skipped—this is the safe way to disable a mod without deleting it.
#
# 1. NNN[-description].patch
#    -> AUTO-APPLIED IN BATCH.
#    -> All standard patches are collected and applied via apply_patches.sh
#       in a single upfront batch BEFORE any shell scripts are executed.
#
# 2. NNN-description.sh
#    -> EXECUTED SEQUENTIALLY.
#    -> Run via `bash` in version-sort order (sort -V) AFTER the auto-patch
#       batch completes. Working directory is set directly to ROOTFS_DIR.
#
# 3. NNN[-description].manual.patch
#    -> ON-DEMAND PATCHING ONLY (NEVER auto-applied).
#    -> Skipped during the initial batch. Designed for staged/cloned files that
#       do not exist in the rootfs until a .sh script creates them.
#    -> Applied from inside any .sh script by calling:
#           apply_mod_patch "NNN-description.manual.patch"
#
# IGNORED / GIBBERISH FILENAMES -- The strict NNN prefix (e.g., 010-) is
# mandatory for automatic discovery and clean linting. Any file dropped into
# mods/ with an arbitrary or gibberish name (such as iamnew.patch, 
# test.manual.patch, or my_script.sh) will fail the validation regex, trigger
# a warning on console, and be completely skipped by the automated pipeline.
# This is intentional so during workflow I can disable any modification by 
# renaming it to something invalid.
#
# Patches may be generated by using gen_patch.sh script.
# ==============================================================================
# --- MANUAL PATCH WORKFLOW ---
# This script uses `.manual.patch` files. Unlike standard `.patch` files,
# manual patches are NEVER auto-applied in the initial batch. They are 
# designed for target files that only exist (or are only in a patchable 
# state) after this script performs initial setup or file staging.
#
# To apply a manual patch at any point in this script, call:
#     apply_mod_patch <patch-filename-or-path>
#
# Example:
#     PATCH1="010-iperf3-tweak.manual.patch"
#     cp /some/source/iperf3 usr/bin/iperf3
#     apply_mod_patch "$PATCH1"
#

set -euo pipefail

# --- Color Logging Helpers ---
C_RESET='\033[0m'
C_GREEN='\033[1;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[1;31m'
C_CYAN='\033[1;36m'

info()  { echo -e "${C_CYAN}  ->${C_RESET} ${1}"; }
ok()    { echo -e "${C_GREEN}  ✓${C_RESET} ${1}"; }
warn()  { echo -e "${C_YELLOW}  !${C_RESET} ${1}"; }
fail()  { echo -e "${C_RED}  ✗ ${1}${C_RESET}" >&2; exit 1; }

# Banner -- use if needed
log_section() {
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo -e "${C_GREEN}$1${C_RESET}"
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo  # Output a blank line for spacing
}

# Working directory is already set to ROOTFS_DIR by apply_mods.sh.
log_section "Replacing Factory Fan Control Script"
info "Running mod: $(basename "$0")..."

# ==============================================================================
# REPLACE FACTORY FAN CONTROL SCRIPT
# ==============================================================================
TARGET_FILE="sbin/temp_ctrl.sh"

info "Overwriting ${TARGET_FILE} with aggressive speed curve..."
cat << 'EOF' > "$TARGET_FILE"
#!/bin/sh
# #################################################################
# Temp ctrl through /sbin/fan_ctrl, aggressive curve fan speed.
# NOTE: Minimum fan speed is 2250 RPM to prevent stalling.
# Netgear telemetry /usr/sbin/fan calls have been stripped.
#
#  Y(rpm)
#  ^                                               * [4100,71'C] TURBO
#  |                                         *
#  |                                    *  [3900,70'C] HIGH
#  |                               *
#  |                          *
#  |                     *
#  |                *
#  |              [2250,45'C] START
#  |       
#  |
#  +--0---25------50------55------60------65------70---71-------> X('C)
#      OFF | --------- LINEAR RAMP --------- | HIGH | TURBO
################################################wallEVA############
ctrl_cycle=$1
float_range=$2
trigger_temp=$3

# ---- Aggressive fan speed curve ----
#  Below 45C :  OFF
#  45C..70C  :  linear ramp 2250 -> 3900 RPM
#  70C..71C  :  HIGH (3900 RPM)
#  >=71C     :  TURBO (4100 RPM)
low_temp=45
high_temp=70
crit_temp=71
low_speed=2250
high_speed=3900
turbo_speed=4100

# Linear slope (RPM per degree C) = (3900-2250)/(70-45) = 1650/25 = 66
kg=$(($((high_speed-low_speed))/$((high_temp-low_temp))))

# This fan binary seems to be related to Netgear telemetry. Ignore this.
# /usr/sbin/fan 1 0 0

if [[ "$float_range" && "$ctrl_cycle" ]];then
    while [ 1 ]; do
        temp_pct2075=`cat /proc/pct2075/temp`
        temp_board=${temp_pct2075%%.*}

        # Decide target speed + fan_mode based on temperature band
        if [ $temp_board -ge $crit_temp ]; then
            # TURBO
            target_speed=$turbo_speed
            fan_mode=1
        elif [ $temp_board -ge $high_temp ]; then
            # HIGH clamp
            target_speed=$high_speed
            fan_mode=1
        elif [ $temp_board -ge $low_temp ]; then
            # Linear ramp: low_speed + slope * (T - low_temp)
            temp_error=$((temp_board-low_temp))
            target_speed=$(($((kg*temp_error))+$low_speed))
            # Clamp (defensive) to prevent stalling or exceeding high_speed
            if [ $target_speed -lt $low_speed ]; then
                target_speed=$low_speed
            fi
            if [ $target_speed -gt $high_speed ]; then
                target_speed=$high_speed
            fi
            fan_mode=1
        else
            # Below ramp start: OFF
            target_speed=0
            fan_mode=0
        fi

        # Honor fan_always_enable: never fully stop the fan
        if [ "x$(/bin/config get fan_always_enable)" = "x1" ]; then
            if [ $target_speed -eq 0 ]; then
                target_speed=$low_speed
                fan_mode=1
            fi
        fi

        # Read current target and compute |delta|
        cur_speed=`cat /sys/bus/i2c/devices/0-003e/fan1_target 2>/dev/null`
        [ -z "$cur_speed" ] && cur_speed=0
        float_error=$((target_speed-cur_speed))
        if [ $float_error -ge 0 ]; then
            float_error=$float_error
        else
            float_error=${float_error##*-}
        fi

        # Apply
        if [ $target_speed -eq 0 ]; then
            # Force stop
            /sbin/fan_ctrl.sh stop $ctrl_cycle
            # Telemetry bloat
            # /usr/sbin/fan 1 0 $ctrl_cycle 
        elif [ $float_error -ge $float_range ] || [ $cur_speed -eq 0 ]; then
            # Significant change (or fan currently off) -> write new target
            /sbin/fan_ctrl.sh start $ctrl_cycle $target_speed
            # Telemetry bloat
            # /usr/sbin/fan 1 $fan_mode $ctrl_cycle 
        else
            # Within hysteresis -> hold current target, let chip maintain
            # Telemetry bloat
            # /usr/sbin/fan 1 2 0
            sleep $ctrl_cycle
        fi
    done
else
    # Telemetry bloat
    # /usr/sbin/fan 1 2 0
    echo "Usage: temp_ctrl.sh [ctrl_cycle] [float_range] [trigger_temp]"
    echo "Note: To avoid fan shock, ctrl_cycle is better to be more than 10 seconds"
    exit 0
fi
EOF

chmod 0755 "$TARGET_FILE"
ok "Aggressive fan control script applied and made executable."


# ==============================================================================
# END OF MODIFICATION LOGIC
# ==============================================================================

ok "Successfully completed $(basename "$0")."
exit 0
