#!/usr/bin/env bash
#
# 003-add-iperf3.sh
#
# Description: Copies the local iperf3 binary into the rootfs, creates an
#              OpenWrt-style init script, and enables it to auto-start on boot.
# Applied by:  apply_mods.sh (runs in version-sort order via `sort -V`)
#
# ==============================================================================
# apply_mods.sh - FILE NAMING CONVENTIONS & EXECUTION RULES
# ==============================================================================
#
# All files inside mods/ MUST begin with exactly three leading digits (NNN).
# Any file with missing digits, wrong lengths, or prefixes (e.g., 'd010-foo.sh')
# is ignored and skipped—this is the safe way to disable a mod without deleting it.
#
# 1. NNN[-description].patch
#    -> AUTO-APPLIED IN BATCH.
#    -> All standard patches are collected and applied via apply_patches.sh
#       in a single upfront batch BEFORE any shell scripts are executed.
#
# 2. NNN-description.sh
#    -> EXECUTED SEQUENTIALLY.
#    -> Run via `bash` in version-sort order (sort -V) AFTER the auto-patch
#       batch completes. Working directory is set directly to ROOTFS_DIR.
#
# 3. NNN[-description].manual.patch
#    -> ON-DEMAND PATCHING ONLY (NEVER auto-applied).
#    -> Skipped during the initial batch. Designed for staged/cloned files that
#       do not exist in the rootfs until a .sh script creates them.
#    -> Applied from inside any .sh script by calling:
#           apply_mod_patch "NNN-description.manual.patch"
#
# IGNORED / GIBBERISH FILENAMES -- The strict NNN prefix (e.g., 010-) is
# mandatory for automatic discovery and clean linting. Any file dropped into
# mods/ with an arbitrary or gibberish name (such as iamnew.patch, 
# test.manual.patch, or my_script.sh) will fail the validation regex, trigger
# a warning on console, and be completely skipped by the automated pipeline.
# This is intentional so during workflow I can disable any modification by 
# renaming it to something invalid.
#
# Patches may be generated by using gen_patch.sh script.
# ==============================================================================
# --- MANUAL PATCH WORKFLOW ---
# This script uses `.manual.patch` files. Unlike standard `.patch` files,
# manual patches are NEVER auto-applied in the initial batch. They are 
# designed for target files that only exist (or are only in a patchable 
# state) after this script performs initial setup or file staging.
#
# To apply a manual patch at any point in this script, call:
#     apply_mod_patch <patch-filename-or-path>
#
# Example:
#     PATCH1="010-iperf3-tweak.manual.patch"
#     cp /some/source/iperf3 usr/bin/iperf3
#     apply_mod_patch "$PATCH1"
#

set -euo pipefail

# --- Color Logging Helpers ---
C_RESET='\033[0m'
C_GREEN='\033[1;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[1;31m'
C_CYAN='\033[1;36m'

info()  { echo -e "${C_CYAN}  ->${C_RESET} ${1}"; }
ok()    { echo -e "${C_GREEN}  ✓${C_RESET} ${1}"; }
warn()  { echo -e "${C_YELLOW}  !${C_RESET} ${1}"; }
fail()  { echo -e "${C_RED}  ✗ ${1}${C_RESET}" >&2; exit 1; }

log_section() {
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo -e "${C_GREEN}$1${C_RESET}"
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo
}

# ==============================================================================
# MODULAR CONFIGURATION
# ==============================================================================
BIN_NAME="iperf3"
MOD_SRC_DIR="iperf3"
SRC_BIN="${MOD_SRC_DIR}/${BIN_NAME}"

TARGET_BIN_REL="usr/bin/$BIN_NAME"            # where THIS script writes, during build
TARGET_BIN_ABS="/usr/bin/$BIN_NAME"           # what the init script invokes, at runtime

TARGET_FILE_REL="etc/init.d/$BIN_NAME"
PID_FILE_ABS="/var/run/$BIN_NAME.pid"         # only ever referenced at runtime

RC_D_REL="etc/rc.d"
START_PRIORITY=99
RC_D_LINK_REL="${RC_D_REL}/S${START_PRIORITY}${BIN_NAME}"

# ==============================================================================
# MAIN LOGIC
# ==============================================================================
log_section "Installing and configuring $BIN_NAME"
info "Running mod: $(basename "$0")..."

# 1. Copy and place the binary
info "Copying $BIN_NAME binary to ${TARGET_BIN_REL}..."

if [ ! -f "${MODS_DIR}/${SRC_BIN}" ]; then
    fail "Local binary not found at mods/${SRC_BIN}. Please download it first!"
fi

copy_mod_file "usr/bin" "$SRC_BIN"
chmod 0755 "$TARGET_BIN_REL"
ok "$BIN_NAME binary installed and made executable."

# 2. Create the init script -- matching Netgear's native samba script style.
#    Uses #!/bin/sh /etc/rc.common, bare start()/stop()/boot() definitions,
#    and explicit dispatch at the bottom.
info "Creating auto-start init script at ${TARGET_FILE_REL}..."
mkdir -p "$(dirname "$TARGET_FILE_REL")"

# Note: EOF is NOT quoted -- variables below expand NOW, at build time, to
# their literal runtime-absolute values (TARGET_BIN_ABS, PID_FILE_ABS,
# BIN_NAME), which is what we want baked into the script permanently.
# \$(...) and \$1 stay escaped so they are evaluated LATER, by the router's 
# own shell at runtime.
cat << EOF > "$TARGET_FILE_REL"
#!/bin/sh /etc/rc.common
# Auto-generated init script for $BIN_NAME

START=$START_PRIORITY

start() {
    echo "Starting $BIN_NAME server in daemon mode..."
    # -s: server mode, -D: daemon, -I: pidfile path
    $TARGET_BIN_ABS -s -D -I $PID_FILE_ABS
}

stop() {
    echo "Stopping $BIN_NAME server..."
    if [ -f "$PID_FILE_ABS" ]; then
        kill \$(cat "$PID_FILE_ABS") 2>/dev/null
        rm -f "$PID_FILE_ABS"
    else
        killall $BIN_NAME 2>/dev/null
    fi
}

boot() {
    # Start in the background so it doesn't delay router boot sequence
    start &
}

[ "\$1" = "start" ] && start
[ "\$1" = "stop" ] && stop
EOF

chmod 0755 "$TARGET_FILE_REL"
ok "Init script created."

# 3. Enable on boot via symlink
info "Creating auto-start symlink in ${RC_D_REL}..."
mkdir -p "$RC_D_REL"
# Symlink TARGET itself (the string "../init.d/$BIN_NAME") is relative to
# wherever the symlink lives once deployed. Only the symlink's own LOCATION 
# needed the REL fix to stay safely inside ROOTFS_DIR during build.
ln -sf "../init.d/$BIN_NAME" "$RC_D_LINK_REL"

ok "$BIN_NAME added permanently and configured to start on boot!"

# ==============================================================================
# END OF MODIFICATION LOGIC
# ==============================================================================
ok "Successfully completed $(basename "$0")."
exit 0
