#!/usr/bin/env bash
#
# 004-custom-vpn-page.sh
#
# Description: Replaces the OEM VPN Client page with a custom WireGuard +
#              OpenVPN dropdown-driven page, plus a NordVPN Setup Wizard.
#              Files are organized in subdirectories under mods/VPN/:
#              - mods/VPN/openvpn/
#              - mods/VPN/wireguard/
#              - mods/VPN/frontend/
#              - mods/VPN/bin/
#              - mods/VPN/Nordvpn_Setup/
# Applied by:  apply_mods.sh (runs in version-sort order via `sort -V`)
#
# ==============================================================================
# apply_mods.sh - FILE NAMING CONVENTIONS & EXECUTION RULES
# ==============================================================================
#
# All files inside mods/ MUST begin with exactly three leading digits (NNN).
# Any file with missing digits, wrong lengths, or prefixes (e.g., 'd010-foo.sh')
# is ignored and skipped—this is the safe way to disable a mod without deleting it.
#
# 1. NNN[-description].patch
#    -> AUTO-APPLIED IN BATCH.
#    -> All standard patches are collected and applied via apply_patches.sh
#       in a single upfront batch BEFORE any shell scripts are executed.
#
# 2. NNN-description.sh
#    -> EXECUTED SEQUENTIALLY.
#    -> Run via `bash` in version-sort order (sort -V) AFTER the auto-patch
#       batch completes. Working directory is set directly to ROOTFS_DIR.
#
# 3. NNN[-description].manual.patch
#    -> ON-DEMAND PATCHING ONLY (NEVER auto-applied).
#    -> Skipped during the initial batch. Designed for staged/cloned files that
#       do not exist in the rootfs until a .sh script creates them.
#    -> Applied from inside any .sh script by calling:
#           apply_mod_patch "NNN-description.manual.patch"
#
# IGNORED / GIBBERISH FILENAMES -- The strict NNN prefix (e.g., 010-) is
# mandatory for automatic discovery and clean linting. Any file dropped into
# mods/ with an arbitrary or gibberish name (such as iamnew.patch, 
# test.manual.patch, or my_script.sh) will fail the validation regex, trigger
# a warning on console, and be completely skipped by the automated pipeline.
# This is intentional so during workflow I can disable any modification by 
# renaming it to something invalid.
#
# Patches may be generated by using gen_patch.sh script.
# ==============================================================================
# --- MANUAL PATCH WORKFLOW ---
# This script uses `.manual.patch` files. Unlike standard `.patch` files,
# manual patches are NEVER auto-applied in the initial batch. They are 
# designed for target files that only exist (or are only in a patchable 
# state) after this script performs initial setup or file staging.
#
# To apply a manual patch at any point in this script, call:
#     apply_mod_patch <patch-filename-or-path>
#
# Example:
#     PATCH1="010-iperf3-tweak.manual.patch"
#     cp /some/source/iperf3 usr/bin/iperf3
#     apply_mod_patch "$PATCH1"
#

set -euo pipefail

C_RESET='\033[0m'
C_GREEN='\033[1;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[1;31m'
C_CYAN='\033[1;36m'

info() { echo -e "${C_CYAN}  ->${C_RESET} ${1}"; }
ok()   { echo -e "${C_GREEN}  ✓${C_RESET} ${1}"; }
warn() { echo -e "${C_YELLOW}  !${C_RESET} ${1}"; }
fail() { echo -e "${C_RED}  ✗ ${1}${C_RESET}" >&2; exit 1; }

log_section() {
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo -e "${C_GREEN}$1${C_RESET}"
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo
}

log_section "Installing Custom VPN Client (WireGuard + OpenVPN + NordVPN Setup)"
info "Running mod: $(basename "$0")..."

# ==============================================================================
# 1. Config & Paths
# ==============================================================================
# Change this variable if you ever rename the mods/VPN folder!
MOD_SRC_DIR="VPN"
MOD_PREFIX="${MOD_SRC_DIR}/"

LIGHTTPD_CONF="etc/lighttpd/conf.d/30-cgi.conf"
CGI_DIR="www/cgi-bin"
VPN_CLIENT_DIR="etc/vpn_client"
INIT_SCRIPT="etc/init.d/custom_vpn"

# Backend logic split by directory
OPENVPN_FILES=(
    openvpn/ovpn_client_custom.env
    openvpn/ovpn_ctrl.sh
    openvpn/ovpn_update_config.sh
)
WIREGUARD_FILES=(
    wireguard/wireguard_client.env
    wireguard/wg_ctrl.sh
    wireguard/wg_update_config.sh
    wireguard/wg_watchdog.sh
    wireguard/wg_selective_route.sh
)
COMMON_FILES=(
    vpn_common.env
    vpn_ctrl.sh
    vpnctl
)
CGI_FILES=(
    frontend/upload_wg.mod
    frontend/upload_ovpn.mod
    frontend/vpn_ctrl.mod
    frontend/vpn_settings.mod
    frontend/vpn_auth.mod
    frontend/vpn_log.mod
)
BIN_FILES=(
    bin/wg
    bin/wireguard.ko
)
NORDVPN_FILES=(
    Nordvpn_Setup/nordvpn_wg_gen.sh
    Nordvpn_Setup/nordvpn_gen.mod
    Nordvpn_Setup/nordvpn_setup.htm
    Nordvpn_Setup/nordvpn_setup.js
)

# ==============================================================================
# 2. Verify all files in mods/<MOD_SRC_DIR>/ subdirectories exist
# ==============================================================================
info "Checking required files in mods/${MOD_SRC_DIR}/ subdirectories..."
ALL_REQUIRED=(
    "${OPENVPN_FILES[@]}"
    "${WIREGUARD_FILES[@]}"
    "${COMMON_FILES[@]}"
    "${CGI_FILES[@]}"
    "${BIN_FILES[@]}"
    "${NORDVPN_FILES[@]}"
    frontend/vpn_client.htm
    custom_vpn.init
)

missing=0
for f in "${ALL_REQUIRED[@]}"; do
    if [ ! -f "${MODS_DIR}/${MOD_SRC_DIR}/${f}" ]; then
        warn "missing mods/${MOD_SRC_DIR}/${f}"
        missing=1
    fi
done
[ "$missing" -eq 0 ] || fail "one or more required files missing from mods/${MOD_SRC_DIR}/ -- see warnings above"
ok "All required files present."

# ==============================================================================
# 3. Patch lighttpd to allow execution of *.mod files
# ==============================================================================
info "Patching lighttpd for .mod CGI support..."
if [ -f "$LIGHTTPD_CONF" ]; then
    sed -i 's/"" => "\/usr\/sbin\/net-cgi"/".mod" => "\/bin\/sh",\n\t\t\t\t\t\t\t\t"" => "\/usr\/sbin\/net-cgi"/g' "$LIGHTTPD_CONF"
    ok "lighttpd patched successfully."
else
    warn "${LIGHTTPD_CONF} not found! Skipping lighttpd patch."
fi

# ==============================================================================
# 4. Backend scripts -> /etc/vpn_client/ (flattened in rootfs target)
# ==============================================================================
info "Copying backend scripts to ${VPN_CLIENT_DIR}..."
copy_mod_file "$VPN_CLIENT_DIR" \
    "${OPENVPN_FILES[@]/#/$MOD_PREFIX}" \
    "${WIREGUARD_FILES[@]/#/$MOD_PREFIX}" \
    "${COMMON_FILES[@]/#/$MOD_PREFIX}"

# Ensure both .sh scripts and the extension-less vpnctl binary are executable
chmod +x "${VPN_CLIENT_DIR}"/*.sh "${VPN_CLIENT_DIR}/vpnctl"
ok "Backend scripts installed."

# ==============================================================================
# 5. CGI endpoints -> /www/cgi-bin/
# ==============================================================================
info "Copying CGI endpoints to ${CGI_DIR}..."
mkdir -p "$CGI_DIR"
copy_mod_file "$CGI_DIR" "${CGI_FILES[@]/#/$MOD_PREFIX}"
chmod +x "${CGI_DIR}"/*.mod
ok "CGI endpoints installed."

# ==============================================================================
# 6. Frontend page -> /www/vpn_client.htm
# ==============================================================================
info "Installing custom VPN frontend page..."
copy_mod_file www "${MOD_SRC_DIR}/frontend/vpn_client.htm"
ok "Frontend page installed."

# ==============================================================================
# 7. WireGuard binary + kernel module
# ==============================================================================
info "Installing wg binary and wireguard.ko..."
copy_mod_file usr/bin "${MOD_SRC_DIR}/bin/wg"
chmod +x usr/bin/wg

KVER_DIR="$(basename "$(ls -d lib/modules/*/ 2>/dev/null | head -1)")"
if [ -z "$KVER_DIR" ] || [ "$KVER_DIR" = "*" ]; then
    fail "could not resolve a kernel version under lib/modules/ -- is this really an unpacked rootfs?"
fi
info "Resolved kernel module dir: lib/modules/${KVER_DIR}"
copy_mod_file "lib/modules/${KVER_DIR}" "${MOD_SRC_DIR}/bin/wireguard.ko"
ok "wireguard.ko installed for kernel ${KVER_DIR}."

# ==============================================================================
# 8. Init script -> /etc/init.d/custom_vpn (+ rc.d symlink)
# ==============================================================================
info "Installing boot-time init script..."
mkdir -p etc/init.d etc/rc.d
copy_mod_file etc/init.d "${MOD_SRC_DIR}/custom_vpn.init"
mv etc/init.d/custom_vpn.init "$INIT_SCRIPT"
chmod +x "$INIT_SCRIPT"
ln -sf ../init.d/custom_vpn etc/rc.d/S61custom_vpn
ok "Init script S61custom_vpn created."

# ==============================================================================
# 9. CLI Wrapper Symlink -> /usr/bin/vpnctl
# ==============================================================================
info "Symlinking vpnctl for global telnet/SSH access..."
mkdir -p usr/bin
ln -sf /etc/vpn_client/vpnctl usr/bin/vpnctl
ok "vpnctl available globally."

# ==============================================================================
# 10. NordVPN Setup Wizard Integration
# ==============================================================================
log_section "Installing NordVPN Setup Wizard"
info "Installing NordVPN backend script, CGI endpoint, and popup page..."

copy_mod_file "${VPN_CLIENT_DIR}" "${MOD_PREFIX}Nordvpn_Setup/nordvpn_wg_gen.sh"
copy_mod_file "${CGI_DIR}" "${MOD_PREFIX}Nordvpn_Setup/nordvpn_gen.mod"
copy_mod_file www "${MOD_PREFIX}Nordvpn_Setup/nordvpn_setup.htm"
copy_mod_file www "${MOD_PREFIX}Nordvpn_Setup/nordvpn_setup.js"

# Set executable permissions
chmod +x "${VPN_CLIENT_DIR}/nordvpn_wg_gen.sh"
chmod +x "${CGI_DIR}/nordvpn_gen.mod"

# Sanitize DOS line endings
sed -i 's/\r$//' \
  "${VPN_CLIENT_DIR}/nordvpn_wg_gen.sh" \
  "${CGI_DIR}/nordvpn_gen.mod" \
  "www/nordvpn_setup.htm" \
  "www/nordvpn_setup.js"

ok "NordVPN files installed and sanitized."

# ==============================================================================
# Done
# ==============================================================================
ok "Custom VPN Suite (WG + OVPN + NordVPN Setup) successfully installed."
exit 0
