#!/usr/bin/env bash
#
# 005-disable-fw-autoupdate.sh
#
# Description: Changes the D2 UpBaseURL endpoint that libfwcheck.so
#              uses for all firmware-check calls (boot-notification,
#              net-cgi -c, and the setup wizard's check_version() tag),
#              by patching the init script that re-sets it every boot.
# Applied by:  apply_mods.sh (runs in version-sort order via `sort -V`)
#
# ==============================================================================
# apply_mods.sh - FILE NAMING CONVENTIONS & EXECUTION RULES
# ==============================================================================
#
# All files inside mods/ MUST begin with exactly three leading digits (NNN).
# Any file with missing digits, wrong lengths, or prefixes (e.g., 'd010-foo.sh')
# is ignored and skipped—this is the safe way to disable a mod without deleting it.
#
# 1. NNN[-description].patch
#    -> AUTO-APPLIED IN BATCH.
#    -> All standard patches are collected and applied via apply_patches.sh
#       in a single upfront batch BEFORE any shell scripts are executed.
#
# 2. NNN-description.sh
#    -> EXECUTED SEQUENTIALLY.
#    -> Run via `bash` in version-sort order (sort -V) AFTER the auto-patch
#       batch completes. Working directory is set directly to ROOTFS_DIR.
#
# 3. NNN[-description].manual.patch
#    -> ON-DEMAND PATCHING ONLY (NEVER auto-applied).
#    -> Skipped during the initial batch. Designed for staged/cloned files that
#       do not exist in the rootfs until a .sh script creates them.
#    -> Applied from inside any .sh script by calling:
#           apply_mod_patch "NNN-description.manual.patch"
#
# IGNORED / GIBBERISH FILENAMES -- The strict NNN prefix (e.g., 010-) is
# mandatory for automatic discovery and clean linting. Any file dropped into
# mods/ with an arbitrary or gibberish name (such as iamnew.patch, 
# test.manual.patch, or my_script.sh) will fail the validation regex, trigger
# a warning on console, and be completely skipped by the automated pipeline.
# This is intentional so during workflow I can disable any modification by 
# renaming it to something invalid.
#
# Patches may be generated by using gen_patch.sh script.
# ==============================================================================
# --- MANUAL PATCH WORKFLOW ---
# This script uses `.manual.patch` files. Unlike standard `.patch` files,
# manual patches are NEVER auto-applied in the initial batch. They are 
# designed for target files that only exist (or are only in a patchable 
# state) after this script performs initial setup or file staging.
#
# To apply a manual patch at any point in this script, call:
#     apply_mod_patch <patch-filename-or-path>
#
# Example:
#     PATCH1="010-iperf3-tweak.manual.patch"
#     cp /some/source/iperf3 usr/bin/iperf3
#     apply_mod_patch "$PATCH1"
#

set -euo pipefail

C_RESET='\033[0m'; C_GREEN='\033[1;32m'; C_YELLOW='\033[1;33m'
C_RED='\033[1;31m'; C_CYAN='\033[1;36m'
info()  { echo -e "${C_CYAN}  ->${C_RESET} ${1}"; }
ok()    { echo -e "${C_GREEN}  ✓${C_RESET} ${1}"; }
warn()  { echo -e "${C_YELLOW}  !${C_RESET} ${1}"; }
fail()  { echo -e "${C_RED}  ✗ ${1}${C_RESET}" >&2; exit 1; }

log_section() {
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo -e "${C_GREEN}$1${C_RESET}"
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo
}

log_section "Disabling auto firmware update permanently ..."
info "Running mod: $(basename "$0")..."

info "Changing D2 UpBaseURL to invalid address (firmware-check endpoint)"
D2_INIT="etc/init.d/d2"
[ -f "$D2_INIT" ] || fail "${D2_INIT} not found -- rootfs layout may have changed."

if grep -q 'UP_BACKEND_BASE=https://devcom.up.netgear.com/UpBackend/' "$D2_INIT"; then
    info "Redirecting UP_BACKEND_BASE to a non-resolving endpoint (RFC 2606 .invalid)..."
    sed -i 's#UP_BACKEND_BASE=https://devcom.up.netgear.com/UpBackend/#UP_BACKEND_BASE=https://update.invalid/UpBackend/#' "$D2_INIT"
    ok "UpBaseURL will now fail at DNS resolution on every boot -- no loopback into net-cgi."
else
    warn "UP_BACKEND_BASE assignment not found in ${D2_INIT} -- already patched, or firmware layout changed. Skipping."
fi

ok "Successfully completed $(basename "$0")."
exit 0