#!/usr/bin/env bash
#
# 006-disable-armor.sh
#
# Description: Replaces armor_init with a streamlined mounting script
#              that executes custom scripts. Also patches etc/init.d/boot
#              (START=10) to clear the dgc_func_have_armor flag at the
#              earliest point config is reloaded -- well before armor_init
#              (START=94) ever runs. Previously this flag was only cleared
#              at the END of armor_init's own boot(), 84 start-priority
#              slots later, which left the flag stale for anything earlier
#              in boot that checks it (suspected cause of first-boot-after-
#              factory-reset weirdness).
#
#              NOTE: armor_init's own mount/ubifs/opt-bitdefender setup is
#              NOT gated by this flag and still runs unconditionally --
#              this only fixes the flag's timing for other consumers.
#
# Applied by:  apply_mods.sh (runs in version-sort order via `sort -V`)
#
# ==============================================================================
# apply_mods.sh - FILE NAMING CONVENTIONS & EXECUTION RULES
# ==============================================================================
#
# All files inside mods/ MUST begin with exactly three leading digits (NNN).
# Any file with missing digits, wrong lengths, or prefixes (e.g., 'd010-foo.sh')
# is ignored and skipped—this is the safe way to disable a mod without deleting it.
#
# 1. NNN[-description].patch
#    -> AUTO-APPLIED IN BATCH.
#    -> All standard patches are collected and applied via apply_patches.sh
#       in a single upfront batch BEFORE any shell scripts are executed.
#
# 2. NNN-description.sh
#    -> EXECUTED SEQUENTIALLY.
#    -> Run via `bash` in version-sort order (sort -V) AFTER the auto-patch
#       batch completes. Working directory is set directly to ROOTFS_DIR.
#
# 3. NNN[-description].manual.patch
#    -> ON-DEMAND PATCHING ONLY (NEVER auto-applied).
#    -> Skipped during the initial batch. Designed for staged/cloned files that
#       do not exist in the rootfs until a .sh script creates them.
#    -> Applied from inside any .sh script by calling:
#           apply_mod_patch "NNN-description.manual.patch"
#
# IGNORED / GIBBERISH FILENAMES -- The strict NNN prefix (e.g., 010-) is
# mandatory for automatic discovery and clean linting. Any file dropped into
# mods/ with an arbitrary or gibberish name (such as iamnew.patch, 
# test.manual.patch, or my_script.sh) will fail the validation regex, trigger
# a warning on console, and be completely skipped by the automated pipeline.
# This is intentional so during workflow I can disable any modification by 
# renaming it to something invalid.
#
# Patches may be generated by using gen_patch.sh script.
# ==============================================================================
# --- MANUAL PATCH WORKFLOW ---
# This script uses `.manual.patch` files. Unlike standard `.patch` files,
# manual patches are NEVER auto-applied in the initial batch. They are 
# designed for target files that only exist (or are only in a patchable 
# state) after this script performs initial setup or file staging.
#
# To apply a manual patch at any point in this script, call:
#     apply_mod_patch <patch-filename-or-path>
#
# Example:
#     PATCH1="010-iperf3-tweak.manual.patch"
#     cp /some/source/iperf3 usr/bin/iperf3
#     apply_mod_patch "$PATCH1"
#

set -euo pipefail

# --- Color Logging Helpers ---
C_RESET='\033[0m'
C_GREEN='\033[1;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[1;31m'
C_CYAN='\033[1;36m'

info()  { echo -e "${C_CYAN}  ->${C_RESET} ${1}"; }
ok()    { echo -e "${C_GREEN}  ✓${C_RESET} ${1}"; }
warn()  { echo -e "${C_YELLOW}  !${C_RESET} ${1}"; }
fail()  { echo -e "${C_RED}  ✗ ${1}${C_RESET}" >&2; exit 1; }

# Banner -- use if needed
log_section() {
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo -e "${C_GREEN}$1${C_RESET}"
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo  # Output a blank line for spacing
}

# Working directory is already set to ROOTFS_DIR by apply_mods.sh.
log_section "Disable armor and enabling mounting netgear volumes without initialization ..."
info "Running mod: $(basename "$0")..."

TARGET_FILE="etc/init.d/armor_init"

info "Updating armor init scripts at ${TARGET_FILE}..."
cat << 'EOF' > "$TARGET_FILE"
#!/bin/sh /etc/rc.common
#To use circle function,please identify the value of "mount_dev"
START=94
boot() {

    if [ -z "$(ubinfo -a |grep vol_armor)" ]; then
        ubimkvol /dev/ubi0 -N vol_armor -s 58MiB
    fi

    mount_dev=`part_dev armor`
    router_reset=`/bin/config get reset_flag`
    partition_type=`cat /flash_type`

    if [ "x$partition_type" != "xEMMC" ]; then
        ubidev=$(ubinfo -a | grep -B5 vol_armor | sed -nr 's/Volume ID:.*\(on (ubi.*)\)/\1/p')
        if [ "$ubidev" = "" -a "$(ubinfo -a | grep vol_ntgrdata)" != "" ]; then
            have_vol_ntgrdata=1
        fi
    fi
    
    if [ -b $mount_dev -a "x$partition_type" = "xEMMC" ];then
        [ "x$mount_dev" != "x" ] && filetype=`blkid $mount_dev |grep -o 'TYPE=.*' |awk -F \" '{print $2}'`
        if [ "x$filetype" != "xext4" -o "$router_reset" != "1" ];then
            mkfs.ext4 $mount_dev
            /bin/config set reset_flag=1
            /bin/config commit
        fi
    elif [ "x$partition_type" != "xEMMC" ]; then
        if [ "$router_reset" != "1" ]; then
            if [ "$have_vol_ntgrdata" = "1" ]; then
                [ -d "/tmp/ntgrdata/armor" ] && rm -rf /tmp/ntgrdata/armor/*
            else
                flash_erase $mount_dev 0 0
            fi
            /bin/config set reset_flag=1
            /bin/config commit
        fi
    fi

    #armor start
    mkdir -p /mnt/bitdefender/ /tmp/opt/
    ln -s /tmp/opt /opt
    ln -s /mnt/bitdefender /opt/bitdefender

    if [ "x`mount |grep '/tmp/mnt/bitdefender'`" = "x" -a "$have_vol_ntgrdata" = "" ]; then
        [ ! -d '/tmp/mnt/bitdefender' ] && mkdir '/opt/bitdefender'
        if [ "x$partition_type" != "xEMMC" ]; then
            mount -t ubifs $ubidev:vol_armor '/opt/bitdefender'
            if [ "x$(mount |grep '/tmp/mnt/bitdefender')" = "x" ]; then
                flash_erase $mount_dev 0 0
                mount -t ubifs $ubidev:vol_armor '/opt/bitdefender'
            fi
        else
            mount $mount_dev '/opt/bitdefender'
            if [ "x$(mount |grep '/tmp/mnt/bitdefender')" = "x" ]; then
                mkfs.ext4 $mount_dev
                mount $mount_dev '/opt/bitdefender'
            fi
        fi
    elif [ "$have_vol_ntgrdata" = "1" ]; then
        [ ! -d "/tmp/ntgrdata/armor" ] && mkdir -p "/tmp/ntgrdata/armor"
        [ -d /mnt/bitdefender/ ] && rm -r /mnt/bitdefender/ && ln -s "/tmp/ntgrdata/armor" '/tmp/mnt/bitdefender'
    fi

    # Create a dedicated folder inside /opt/bitdefender for custom scripts
    CUSTOM_SCRIPTS_DIR="/opt/bitdefender/custom-scripts"
    mkdir -p "$CUSTOM_SCRIPTS_DIR"

    # Execute all the custom scripts there on boot
    if [ -d "$CUSTOM_SCRIPTS_DIR" ]; then
        for script in "$CUSTOM_SCRIPTS_DIR"/*.sh; do
            [ -f "$script" ] && sh "$script" &
        done
    fi

    # NOTE: dgc_func_have_armor is now disabled much earlier, in
    # etc/init.d/boot (START=10) -- see the etc/init.d/boot patch section
    # below in this same mod script. Left disabled here intentionally to
    # avoid duplicating the config get/set/commit twice per boot.

}   

EOF

chmod 0755 "$TARGET_FILE"
ok "armor_init wrapper created and assigned 0755 permissions."

# ==============================================================================
# PATCH etc/init.d/boot: DISABLE ARMOR FLAG AT START=10 (BEFORE armor_init)
# ==============================================================================
BOOT_FILE="etc/init.d/boot"

[ -f "$BOOT_FILE" ] || fail "${BOOT_FILE} not found -- rootfs layout may have changed."

if grep -q "dgc_func_have_armor" "$BOOT_FILE"; then
    warn "${BOOT_FILE} already references dgc_func_have_armor -- already patched. Skipping."
else
    info "Inserting early armor-disable block into ${BOOT_FILE} (after reload_config)..."

    grep -q '/sbin/reload_config' "$BOOT_FILE" || fail "Anchor '/sbin/reload_config' not found in ${BOOT_FILE} -- refusing to insert blind."

    INSERT_FILE=$(mktemp)
    printf '\n\t# Permanently disable Bitdefender Armor (moved here from armor_init'"'"'s boot()\n\t# so the flag is cleared at START=10, well before armor_init'"'"'s START=94\n\t# mount/ubifs logic ever runs)\n\tif [ "$(/bin/config get dgc_func_have_armor)" = "1" ]; then\n\t\t/bin/config set dgc_func_have_armor=0\n\t\t/bin/config commit\n\tfi\n' > "$INSERT_FILE"

    sed -i "/\/sbin\/reload_config/r $INSERT_FILE" "$BOOT_FILE"
    rm -f "$INSERT_FILE"

    ok "dgc_func_have_armor now cleared at START=10, before armor_init runs."
fi

# ==============================================================================
# END OF MODIFICATION LOGIC
# ==============================================================================

ok "Successfully completed $(basename "$0")."
exit 0
