#!/usr/bin/env bash
#
# NNN-description.sh
#
# Description: Briefly explain what this script and its manual patches do.
# Applied by:  apply_mods.sh (runs in version-sort order via `sort -V`)
#
# ==============================================================================
# apply_mods.sh - FILE NAMING CONVENTIONS & EXECUTION RULES
# ==============================================================================
#
# All files inside mods/ MUST begin with exactly three leading digits (NNN).
# Any file with missing digits, wrong lengths, or prefixes (e.g., 'd010-foo.sh')
# is ignored and skipped—this is the safe way to disable a mod without deleting it.
#
# 1. NNN[-description].patch
#    -> AUTO-APPLIED IN BATCH.
#    -> All standard patches are collected and applied via apply_patches.sh
#       in a single upfront batch BEFORE any shell scripts are executed.
#
# 2. NNN-description.sh
#    -> EXECUTED SEQUENTIALLY.
#    -> Run via `bash` in version-sort order (sort -V) AFTER the auto-patch
#       batch completes. Working directory is set directly to ROOTFS_DIR.
#
# 3. NNN[-description].manual.patch
#    -> ON-DEMAND PATCHING ONLY (NEVER auto-applied).
#    -> Skipped during the initial batch. Designed for staged/cloned files that
#       do not exist in the rootfs until a .sh script creates them.
#    -> Applied from inside any .sh script by calling:
#           apply_mod_patch "NNN-description.manual.patch"
#
# IGNORED / GIBBERISH FILENAMES -- The strict NNN prefix (e.g., 010-) is
# mandatory for automatic discovery and clean linting. Any file dropped into
# mods/ with an arbitrary or gibberish name (such as iamnew.patch, 
# test.manual.patch, or my_script.sh) will fail the validation regex, trigger
# a warning on console, and be completely skipped by the automated pipeline.
# This is intentional so during workflow I can disable any modification by 
# renaming it to something invalid.
#
# Patches may be generated by using gen_patch.sh script.
# ==============================================================================
# --- MANUAL PATCH WORKFLOW ---
# This script uses `.manual.patch` files. Unlike standard `.patch` files,
# manual patches are NEVER auto-applied in the initial batch. They are 
# designed for target files that only exist (or are only in a patchable 
# state) after this script performs initial setup or file staging.
#
# To apply a manual patch at any point in this script, call:
#     apply_mod_patch <patch-filename-or-path>
#
# Example:
#     PATCH1="010-iperf3-tweak.manual.patch"
#     cp /some/source/iperf3 usr/bin/iperf3
#     apply_mod_patch "$PATCH1"
#

set -euo pipefail

# --- Color Logging Helpers ---
C_RESET='\033[0m'
C_GREEN='\033[1;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[1;31m'
C_CYAN='\033[1;36m'

info()  { echo -e "${C_CYAN}  ->${C_RESET} ${1}"; }
ok()    { echo -e "${C_GREEN}  ✓${C_RESET} ${1}"; }
warn()  { echo -e "${C_YELLOW}  !${C_RESET} ${1}"; }
fail()  { echo -e "${C_RED}  ✗ ${1}${C_RESET}" >&2; exit 1; }

# Banner -- use if needed
log_section() {
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo -e "${C_GREEN}$1${C_RESET}"
  echo -e "${C_CYAN}======================================${C_RESET}"
  echo  # Output a blank line for spacing
}

# Working directory is already set to ROOTFS_DIR by apply_mods.sh.
info "Running mod: $(basename "$0")..."

# ==============================================================================
# 1. DEFINE MANUAL PATCHES
# ==============================================================================
# Names must match NNN[-description].manual.patch inside the mods/ directory.
PATCH1="010-iperf3-tweak.manual.patch"
PATCH2="010-iperf3-other.manual.patch"

# ==============================================================================
# 2. STAGE FILES & APPLY FIRST PATCH
# ==============================================================================
# Example: Copying an external binary/config into the rootfs before patching it.
TARGET_BIN="usr/bin/iperf3"

info "Staging ${TARGET_BIN}..."
# cp "/path/to/external/source/iperf3" "$TARGET_BIN"
# chmod 0755 "$TARGET_BIN"

info "Applying primary manual patch..."
# apply_mod_patch "$PATCH1"
ok "Primary patch applied successfully."

# ==============================================================================
# 3. INTERMEDIATE WORK & SECONDARY PATCH
# ==============================================================================
# Perform any intermediate file manipulations, symlinks, or directory creation.

info "Performing intermediate configuration work..."
# mkdir -p "etc/iperf3"
# touch "etc/iperf3/custom.conf"

info "Applying secondary manual patch..."
# apply_mod_patch "$PATCH2"
ok "Secondary patch applied successfully."

# ==============================================================================
# END OF MODIFICATION LOGIC
# ==============================================================================

ok "Successfully completed $(basename "$0")."
exit 0
