obj-y   := hw29765589p0p512p1024p4x4p8x8.o
obj-y	+= clock.o
obj-y	+= cmd_bootqca.o
obj-y += cmd_sec_auth.o
obj-$(CONFIG_SMP_CMD_SUPPORT)	+= cmd_runmulticore.o
obj-y += fdt_fixup.o
obj-$(CONFIG_QCA_APPSBL_DLOAD) += crashdump.o
